defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

optimizer:
  lr: 0.001

scheduler:
  decay_rate: 0.9
  decay_steps: 200

training:
  rec_results_freq : 10000
  rec_constraint_freq: 10000
  max_steps : 20000

batch_size:
  inlet: 20000
  outlet: 10000
  no_slip: 20000
  interior: 30000
  num_integral_continuity: 5
  integral_continuity: 80000
